### ISSUE TITLE
Netlify deploy failed

### ISSUE THREAD

**Issue by osaaso3** [HillPhelmuth/WhiteBoard#6]
Hi
Deployment to Netlify failed. It might be due to Azure module in the project.
Could you make the dependency to Azure optional?
Thanks

**Comment by osaaso3** [comment]
It can be deployed when API module is removed.

**Comment by HillPhelmuth** [comment]
The Api is an Azure Functions app, so the only static hosting service that will support both projects is Azure Static Web Apps.
I've never used Netlify, but you should be able to replicate the services in the Api project. If you set up your own separately hosted Azure Function, Storage and cosmos db, you'd only need to change the connection strings in the Api project, and the endpoint url in StorageClient.cs.
The Authentication service might be a little harder to replace though. Azure Static Web App service manages the authentication with the 4 providers I use, and I don't know if Netlify offers anything similar.

**Comment by osaaso3** [comment]
Thanks, good info.

**Comment by osaaso3** [comment]
closing, thanks!
